## TF Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.4.0


In [3]:
#tensor = n-dimensional array

In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello) #= tensor

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    #Everything here is tensorflow operation
    #Opens the session, runs the block of code and ends it
    result = sess.run(hello + world)

In [12]:
print(result) #b: bytes literal

b'Hello World'


In [13]:
a = tf.constant(10)

In [14]:
b = tf.constant(20)

In [15]:
type(a)

tensorflow.python.framework.ops.Tensor

In [16]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [17]:
a + b #hasn't executed the task yet since we didn't run this in a session

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [19]:
result

30

In [20]:
const = tf.constant(10)

In [23]:
fill_mat = tf.fill((4,4), 10) #creates a tensor filled with firstparam dimension and secondparam value

In [25]:
myzeroes = tf.zeros((4,4))

In [26]:
myones = tf.ones((4,4))

In [27]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [29]:
myrandu = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [31]:
my_ops = [const, fill_mat, myzeroes, myones, myrandn, myrandu]    

In [32]:
#interactive session
sess = tf.InteractiveSession()

In [36]:
for op in my_ops:
    print(sess.run(op)) #op.eval() same
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.9854269   1.1135504  -2.0032887  -0.22772306]
 [ 0.20786144 -1.3005745  -0.1787202  -0.38047245]
 [ 0.8463127  -0.31557643 -1.1482254   0.34347472]
 [ 1.7861046   0.49727446  0.759021    1.2146593 ]]


[[0.58723664 0.42010045 0.73651636 0.31701636]
 [0.22134304 0.87324715 0.15629542 0.859264  ]
 [0.9109005  0.59174573 0.15344882 0.22549617]
 [0.15790546 0.4702444  0.8673955  0.98150325]]




In [37]:
a = tf.constant([[1,2],
                [3,4]])

In [38]:
a.get_shape() #2 by 2

TensorShape([Dimension(2), Dimension(2)])

In [39]:
b = tf.constant([[10], [100]])

In [40]:
b.get_shape() # 2 by 1

TensorShape([Dimension(2), Dimension(1)])

In [43]:
result = tf.matmul(a, b) #matrix multiplication

In [42]:
sess.run(result)

array([[210],
       [430]])

In [44]:
result.eval()

array([[210],
       [430]])